# Generated by Django 4.1 on 2022-12-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments", options={"verbose_name_plural": "Comments"},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="tag",
            field=models.ManyToManyField(related_name="tag", to="blog.tag"),
        ),
    ]
