# Generated by Django 4.1 on 2022-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comments_options_alter_blogpost_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
